<a href="https://colab.research.google.com/github/andreupslpornelas/MineriaDeDatos/blob/main/Mineria_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de datos

## Primer parcial

### Introducción

#### Conceptos

##### La ciencia de datos es un campo interdisciplinario que utiliza métodos científicos, procesos, algoritmos y sistemas para extraer conocimientos y patrones accionables a partir de datos (tanto estructurados como no estructurados).

#### Ciencia de datos

### IPython Magic Commands

In [ ]:
In [8]: %timeit L = [n ** 2 for n in range(1000)]

The slowest run took 4.74 times longer than the fastest. This could mean that an intermediate result is being cached.
125 µs ± 86.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%%timeit
L = []
for n in range(1000):
      L.append(n ** 2)

73.7 µs ± 948 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data

/content/sample_data


In [ ]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '3e8838bda10d',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

### Understanding Data Types in Python

In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### The Basics of NumPy Arrays

In [1]:
import numpy as np

In [3]:
np.random.seed(0)  # seed for reproducibility

In [2]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [4]:
print("x3 ndim: ", x3.ndim) #Dimensión del espacio
print("x3 shape:", x3.shape) # Cada una de las logitudes
print("x3 size: ", x3.size) #Entrega el volumen

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
print("dtype:", x3.dtype)

dtype: int64


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


### Array Indexing: Accessing Single Elements

In [7]:
x1 #imprime el objeto completo

array([6, 1, 0, 0, 4, 1])

In [10]:
x1[0] # Muesta su indexación por dimensión

np.int64(6)

In [11]:
x1[4]

np.int64(4)

In [12]:
x1[-1] #Lista inversa

np.int64(1)

In [13]:
x2

array([[1, 4, 5, 1],
       [8, 8, 0, 9],
       [6, 6, 9, 3]])

In [14]:
x2[0, 0]

np.int64(1)

In [15]:
x2[0, 2]

np.int64(5)

In [16]:
x2[2, -1]

np.int64(3)

In [18]:
x2[0, 0] = 12
x2

array([[12,  4,  5,  1],
       [ 8,  8,  0,  9],
       [ 6,  6,  9,  3]])

### Estadística básica

#### Media (Mean)

In [19]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


#### Promedio (Average) y Promedio Ponderado

In [21]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


#### Mediana

In [22]:
mediana = np.median(data)
print(mediana)

3.0


#### Varianza y Desviación Estándar

In [24]:
varianza = np.var(data)
desviacion = np.std(data)
print(varianza)
print(desviacion)

2.0
1.4142135623730951


####  Correlación